FROM python:3.8

WORKDIR /tensorflow_src
RUN git clone https://github.com/tensorflow/tensorflow.git .
RUN git checkout refs/tags/v2.6.0

RUN apt-get update
RUN apt-get install -y nodejs npm
RUN npm install -g @bazel/bazelisk

RUN pip install -U --user pip numpy==1.19.2 wheel
RUN pip install -U --user keras_preprocessing --no-deps

# MEMO
# Tensorflowのビルドに関しては公式ドキュメントを参照